
package CoffeeShop.Views;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class AdminUI extends javax.swing.JFrame {

    private DefaultTableModel model;
    private javax.swing.JButton addMenuItem;
    private javax.swing.JLabel adminCustomerSearchLabel;
    private javax.swing.JTabbedPane adminTabs;
    private javax.swing.JRadioButton allMenu;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JRadioButton categoryDessert;
    private javax.swing.JRadioButton categoryDrinks;
    private javax.swing.JRadioButton categoryMainCourse;
    private javax.swing.JRadioButton categoryStarters;
    private javax.swing.JPanel customerTab;
    private javax.swing.JButton deleteMenuItem;
    private javax.swing.JTextArea display;
    private javax.swing.JTextArea displayNewItem;
    private javax.swing.JTextField info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable menuItems;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JTextField menuSearch;
    private javax.swing.JLabel menuSearchLabel;
    private javax.swing.JPanel menuTab;
    private javax.swing.JTextField newCost;
    private javax.swing.JTextField newItem;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchSales;
    private javax.swing.JButton viewAll;
    private javax.swing.JButton viewCustomerOrderHistory;
    private javax.swing.JButton viewCustomers;
    private javax.swing.JButton viewOrders;

    /**
     * Creates new form
     */
    public AdminUI() {
        initComponents();
        model = (DefaultTableModel) this.menuItems.getModel();
        ButtonGroup group = new ButtonGroup();
        group.add(categoryDessert);
        group.add(categoryDrinks);
        group.add(categoryMainCourse);
        group.add(categoryStarters);
        group.add(allMenu);
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public JTextArea getDisplay() {
        return display;
    }

    public JTextArea getDisplayNewItem() {
        return displayNewItem;
    }

    public JTextField getInfo() {
        return info;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JTable getMenuItems() {
        return menuItems;
    }

    public JTextField getMenuSearch() {
        return menuSearch;
    }

    public JTextField getNewCost() {
        return newCost;
    }

    public JTextField getNewItem() {
        return newItem;
    }

    public JTextField getSearchSales() {
        return searchSales;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminTabs = new javax.swing.JTabbedPane();
        menuTab = new javax.swing.JPanel();
        menuSearchLabel = new javax.swing.JLabel();
        menuSearch = new javax.swing.JTextField();
        menuScrollPane = new javax.swing.JScrollPane();
        menuItems = new javax.swing.JTable();
        categoriesLabel = new javax.swing.JLabel();
        categoryStarters = new javax.swing.JRadioButton();
        categoryMainCourse = new javax.swing.JRadioButton();
        categoryDessert = new javax.swing.JRadioButton();
        categoryDrinks = new javax.swing.JRadioButton();
        addMenuItem = new javax.swing.JButton();
        search = new javax.swing.JButton();
        info = new javax.swing.JTextField();
        deleteMenuItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayNewItem = new javax.swing.JTextArea();
        newItem = new javax.swing.JTextField();
        newCost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        allMenu = new javax.swing.JRadioButton();
        customerTab = new javax.swing.JPanel();
        adminCustomerSearchLabel = new javax.swing.JLabel();
        searchSales = new javax.swing.JTextField();
        viewCustomerOrderHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        viewCustomers = new javax.swing.JButton();
        viewOrders = new javax.swing.JButton();
        viewAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin");
        setName("AdminUI"); // NOI18N
        setResizable(false);

        menuSearchLabel.setText("Search");

        menuItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Description", "Price", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuItems.setColumnSelectionAllowed(true);
        menuItems.getTableHeader().setReorderingAllowed(false);
        menuScrollPane.setViewportView(menuItems);
        menuItems.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (menuItems.getColumnModel().getColumnCount() > 0) {
            menuItems.getColumnModel().getColumn(0).setResizable(false);
            menuItems.getColumnModel().getColumn(0).setPreferredWidth(25);
            menuItems.getColumnModel().getColumn(1).setResizable(false);
            menuItems.getColumnModel().getColumn(1).setPreferredWidth(70);
            menuItems.getColumnModel().getColumn(2).setResizable(false);
            menuItems.getColumnModel().getColumn(3).setResizable(false);
        }

        categoryStarters.setText("Starters");
        categoryMainCourse.setText("Main Course");
        categoryDessert.setText("Dessert");
        categoryDrinks.setText("Drinks");
        addMenuItem.setText("Add");
        search.setText("Search");
        deleteMenuItem.setText("Delete");
        allMenu.setText("All");

        viewCustomers.setText("View Customers");
        viewOrders.setText("View Orders");
        viewAll.setText("View All");
        adminCustomerSearchLabel.setText("Search");
        viewCustomerOrderHistory.setText("Search Item history");

        info.setEditable(false);
        info.setEnabled(false);

        displayNewItem.setEditable(false);
        displayNewItem.setColumns(8);
        displayNewItem.setRows(3);
        displayNewItem.setTabSize(3);
        displayNewItem.setAutoscrolls(false);
        displayNewItem.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        displayNewItem.setEnabled(false);
        jScrollPane2.setViewportView(displayNewItem);

        jLabel2.setText("Enter new order Item");

        jLabel3.setText("Enter new item cost");

        javax.swing.GroupLayout menuTabLayout = new javax.swing.GroupLayout(menuTab);
        menuTab.setLayout(menuTabLayout);
        menuTabLayout.setHorizontalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuTabLayout.createSequentialGroup()
                                .addComponent(categoryStarters)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryMainCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryDessert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryDrinks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allMenu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(menuTabLayout.createSequentialGroup()
                                .addComponent(menuSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(menuTabLayout.createSequentialGroup()
                                .addComponent(addMenuItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteMenuItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(info))
                            .addComponent(menuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(newItem)
                            .addComponent(newCost)
                            .addGroup(menuTabLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        menuTabLayout.setVerticalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTabLayout.createSequentialGroup()
                .addComponent(categoriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addGap(5, 5, 5)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryMainCourse)
                    .addComponent(categoryStarters)
                    .addComponent(categoryDessert)
                    .addComponent(categoryDrinks)
                    .addComponent(allMenu))
                .addGap(9, 9, 9)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(newItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(newCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMenuItem)
                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteMenuItem))
                .addContainerGap())
        );

        adminTabs.addTab("Menu", menuTab);

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        jLabel1.setText("info");

        javax.swing.GroupLayout customerTabLayout = new javax.swing.GroupLayout(customerTab);
        customerTab.setLayout(customerTabLayout);
        customerTabLayout.setHorizontalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTabLayout.createSequentialGroup()
                        .addComponent(adminCustomerSearchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchSales, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCustomerOrderHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCustomers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewOrders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        customerTabLayout.setVerticalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchSales, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminCustomerSearchLabel)
                    .addComponent(viewCustomerOrderHistory)
                    .addComponent(viewCustomers)
                    .addComponent(viewOrders)
                    .addComponent(viewAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminTabs.addTab("Order History", customerTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adminTabs.getAccessibleContext().setAccessibleName("Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCategoryDessertActionListener(ActionListener al ) {
        this.categoryDessert.addActionListener(al);
    }

    public void setCategoryDrinksActionListener(ActionListener al) {
        this.categoryDrinks.addActionListener(al);
    }

    public void setCategoryStartersActionListener(ActionListener al) {
        this.categoryStarters.addActionListener(al);
    }

    public void setCategoryMainCourseActionListener(ActionListener al) {
        this.categoryMainCourse.addActionListener(al);
    }

    public void setAddMenuItemActionListener(ActionListener al) {
        this.addMenuItem.addActionListener(al);
    }

    public void setSearchActionListener(ActionListener al) {
        this.search.addActionListener(al);
    }

    public void setDeleteMenuItemActionListener(ActionListener al) {
        this.deleteMenuItem.addActionListener(al);
    }

    public void setAllMenuActionListener(ActionListener al) {
        this.allMenu.addActionListener(al);
    }

    public void setViewCustomersActionListener(ActionListener al) {
        this.viewCustomers.addActionListener(al);
    }

    public void setViewOrdersActionListener(ActionListener al) {
        this.viewOrders.addActionListener(al);
    }

    public void setViewAllActionListener(ActionListener al) {
        this.viewAll.addActionListener(al);
    }

    public void setViewCustomerOrderHistoryActionListener(ActionListener al) {
        this.viewCustomerOrderHistory.addActionListener(al);
    }

    public void setMenuItemsMouseListener(MouseAdapter ma) {
        this.menuItems.addMouseListener(ma);
    }

}
