/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 package CoffeeShop;

import CoffeeShop.Controller.CoffeeShopController;

public class CoffeeShopManager {

    public static void main(String[] args) {
        new CoffeeShopController().showGUI();
    }
}

