/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 package CoffeeShop;

import CoffeeShop.Views.CoffeeShopGUI;

public class CoffeeShopManager {

    public static void main(String[] args) {
        new CoffeeShopGUI().showGUI();
    }
}

